var DJSON = {
  data:[{
    styleName:'鞋跟',
    styleId:'Heel',
    mode:[{
      styleId:'Heel1',
      styleName:'粗跟款',
      mode:[{
    	  styleName:'跟',
      },
      {
    	  styleId:'Heel11',
          styleName:'大底',
          mode:[{
            },{
              styleName:'大底边'
            },{
              styleName:'天皮'
            }]
      }],
    },{
        styleId:'Heel2',
        styleName:'细跟款',
        mode:[{
      	  styleName:'跟',
        },
        {
      	  styleId:'Heel22',
            styleName:'大底',
            mode:[{
              },{
                styleName:'大底边'
              },{
                styleName:'天皮'
              }]
        }],
      }]
  },{
    styleName:'鞋面',
    styleId:'Upper',
    mode:[{
      styleId:'Upper1',
      styleName:'尖头单鞋',
      mode:[{
        styleName:'鞋面',
      },
      {
        styleName:'内里和垫脚',
      },
      {
        styleId:'Upper11',
        styleName:'心形装饰',
        mode:[{
          styleName:'钻'
        },{
          styleName:'底垫'
        }]
      }]
    },{
        styleId:'Upper2',
        styleName:'圆头单鞋',
        mode:[{
          styleName:'鞋面',
        },
        {
          styleName:'内里和垫脚',
        },
        {
          styleId:'Upper21',
          styleName:'心形装饰 ',
          mode:[{
            styleName:'钻'
          },{
            styleName:'底垫'
          }]
        }]
      }
    ]}
  ],
  expandedKeys: ['Heel','Heel1','Heel11','Heel2','Heel21','Upper','Upper1','Upper11',"Upper2","Upper21"],
};
export default DJSON;
